# Generated by Django 2.0.3 on 2018-05-02 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20180501_2116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchangestatus',
            name='name',
        ),
        migrations.AddField(
            model_name='exchangestatus',
            name='message_when_initiator',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='exchangestatus',
            name='message_when_receiver',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
