# Generated by Django 2.0.3 on 2018-05-05 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20180502_1047'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_from_initiator', models.BooleanField()),
                ('message', models.CharField(max_length=500)),
                ('date_sent', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='exchange',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.ExchangeStatus'),
        ),
        migrations.AddField(
            model_name='exchangemessage',
            name='exchange',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Exchange'),
        ),
    ]
