# Generated by Django 2.0.4 on 2018-05-19 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_book_is_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('bookId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.Book')),
            ],
        ),
    ]
